/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.kaytea.portfolioTest

import dev.kaytea.portfolio.main
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
}
